sudo: required

language: python

python:
    - "3.6"

services:
  - postgresql
  - docker
  
before_script:
  - psql -c 'create database roombnb;' -U postgres
  - python manage.py database migrate

install:
    - pip install -r deploy/requirements.txt

script:
    - pytest
