sudo: required

language: python

python:
  - "3.5"

services:
  - postgresql

install:
  - apt-get update && apt upgrade -y
  - apt-get install sshpass
  - pip3 install -r deploy/requirements.txt

before_script:
  - psql -c "CREATE USER test_user WITH PASSWORD 'password';" -U postgres
  - psql -c "ALTER USER test_user CREATEDB;" -U postgres

script:
  - python3 manage.py test

after_success:
  - sshpass -p $deploy_password ssh alejandrohall@rentinpeace.ml './deploy develop > deploy.log'
