sudo: required

language: python

python:
  - "3.6"

services:
  - postgresql
  - docker
  
before_script:
  - psql -c 'create database roombnb_test;' -U postgres
  #- psql -c "CREATE USER roombnb_user WITH PASSWORD 'roombnb_db_password';" -U postgres
  - python manage.py migrate
  - python manage.py loaddata deploy/populate.json

install:
  - pip install -r deploy/requirements.txt

script:
  - python manage.py test RoomBnB.tests
