sudo: required

language: python

python:
  - "3.5"

services:
  - postgresql

addons:
  ssh_known_hosts:
    - rentinpeace.ml
  apt:
    packages:
    - sshpass

install:
  - pip3 install -r deploy/requirements.txt

before_script:
  - psql -c "CREATE USER test_user WITH PASSWORD 'password';" -U postgres
  - psql -c "ALTER USER test_user CREATEDB;" -U postgres

script:
  - python3 manage.py test

after_success:
  - curl http://rentinpeace.ml:30000/deploy/develop?key=$DEPLOY_KEY
