sudo: required

language: python

python:
  - "3.5"

services:
  - postgresql

before_script:
  - psql -c 'create database test;' -U postgres
  - psql -c "CREATE USER user WITH PASSWORD password;" -U postgres
  - psql -c 'grant all privileges on database test to user;' -U postgres
  - python manage.py migrate

install:
  - pip3 install -r deploy/requirements.txt

script:
  - python3 manage.py test
