sudo: required

language: python

python:
  - "3.5"

services:
  - postgresql

before_script:
  - psql -c "CREATE USER test_user WITH PASSWORD 'password';" -U postgres
  - psql -c "ALTER USER test_user CREATEDB;" -U postgres

install:
  - pip3 install -r deploy/requirements.txt

script:
  - python3 manage.py test
