# Generated by Django 2.0.2 on 2018-03-22 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RoomBnB', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='temporal_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='RoomBnB.Profile'),
        ),
    ]
