# Generated by Django 2.0.2 on 2018-03-13 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('RoomBnB', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='')),
                ('date_signed', models.DateField(auto_now_add=True)),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='landlord', to='RoomBnB.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=500)),
                ('pictures', models.ImageField(upload_to='')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RoomBnB.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('date', models.DateField(auto_now_add=True)),
                ('rating', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=500)),
                ('price', models.FloatField()),
                ('pictures', models.ImageField(upload_to='')),
                ('belong_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RoomBnB.Flat')),
                ('temporal_owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='RoomBnB.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='FlatReview',
            fields=[
                ('review_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='RoomBnB.Review')),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RoomBnB.Flat')),
            ],
            bases=('RoomBnB.review',),
        ),
        migrations.CreateModel(
            name='RoomReview',
            fields=[
                ('review_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='RoomBnB.Review')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RoomBnB.Room')),
            ],
            bases=('RoomBnB.review',),
        ),
        migrations.CreateModel(
            name='UserReview',
            fields=[
                ('review_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='RoomBnB.Review')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('RoomBnB.review',),
        ),
        migrations.AddField(
            model_name='contract',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='RoomBnB.Room'),
        ),
        migrations.AddField(
            model_name='contract',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tenant', to='RoomBnB.Profile'),
        ),
        migrations.AddField(
            model_name='payment',
            name='contract',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='RoomBnB.Contract'),
        ),
    ]
