# Generated by Django 2.0.2 on 2018-04-02 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RoomBnB', '0003_auto_20180323_1031'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlatProperties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elevator', models.BooleanField(default=False)),
                ('washdisher', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RoomProperties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balcony', models.BooleanField(default=False)),
                ('window', models.BooleanField(default=False)),
                ('air_conditioner', models.BooleanField(default=False)),
                ('bed', models.CharField(choices=[('1', 'Couple'), ('2', 'Single'), ('3', 'Sofa'), ('4', 'None')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='UserProperties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smoker', models.BooleanField(default=False)),
                ('pets', models.BooleanField(default=False)),
                ('sporty', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=1)),
                ('gamer', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=1)),
                ('sociable', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=1)),
                ('degree', models.CharField(choices=[('1', 'Enfermeria'), ('2', 'Ing. Informatica'), ('3', 'Medicina'), ('4', 'Biologia'), ('5', 'Arquitectura')], max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='creditcard',
            name='user',
        ),
        migrations.RemoveField(
            model_name='properties',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='credit_card',
        ),
        migrations.AddField(
            model_name='flat',
            name='picture',
            field=models.ImageField(default='pics/flat/default.jpg', upload_to='pics/flat/'),
        ),
        migrations.AddField(
            model_name='room',
            name='picture',
            field=models.ImageField(default='pics/room/default.png', upload_to='pics/room/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='pics/profile/default.png', upload_to='pics/profile/'),
        ),
        migrations.DeleteModel(
            name='CreditCard',
        ),
        migrations.DeleteModel(
            name='Properties',
        ),
        migrations.AddField(
            model_name='userproperties',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='RoomBnB.Profile'),
        ),
        migrations.AddField(
            model_name='roomproperties',
            name='room',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='RoomBnB.Room'),
        ),
    ]
