# Generated by Django 2.0.2 on 2018-04-02 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RoomBnB', '0004_auto_20180402_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='flatproperties',
            name='flat',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='RoomBnB.Flat'),
            preserve_default=False,
        ),
    ]
