# Generated by Django 2.0.2 on 2018-04-02 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoomBnB', '0005_flatproperties_flat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomproperties',
            name='bed',
            field=models.CharField(choices=[('1', 'Couple'), ('2', 'Single'), ('3', 'Sofa'), ('4', 'None')], default=2, max_length=1),
        ),
    ]
