# Generated by Django 2.0.2 on 2018-04-02 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoomBnB', '0006_auto_20180402_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='picture',
            field=models.ImageField(default='flat/default.jpg', upload_to='flat/'),
        ),
    ]
