# Generated by Django 2.0.2 on 2018-04-02 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoomBnB', '0007_auto_20180402_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='profile/default.png', upload_to='profile/'),
        ),
        migrations.AlterField(
            model_name='room',
            name='picture',
            field=models.ImageField(default='room/default.png', upload_to='room/'),
        ),
    ]
