# Generated by Django 2.0.2 on 2018-04-02 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoomBnB', '0008_auto_20180402_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='picture',
            field=models.ImageField(default='flat/generic/default.jpg', upload_to='flat/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='profile/generic/default.png', upload_to='profile/'),
        ),
        migrations.AlterField(
            model_name='room',
            name='picture',
            field=models.ImageField(default='room/generic/default.jpg', upload_to='room/'),
        ),
    ]
